### ISSUE TITLE
Replace LESS with SCSS

### ISSUE THREAD

**Issue by olliebennett** [scott/helpy#45]
This has a few benefits:

- We can remove `therubyracer` and therefore the `libv8` dependency, which are very clunky, and arguably overkill!
- SCSS has become the prevalent CSS extension (vs. LESS).
- Twitter Bootstrap is actually moving to SCSS for the next version and [Bootstrapv3 support](https://github.com/twbs/bootstrap-sass) is in place already.

My cursory glance indicates that the codebase is using only basic LESS constructs, which means it should be quick to switch to SCSS. Would you consider accepting a PR providing this refactor?

**Comment by scott** [comment]
Yes I did think of doing this especially since Bootstrap is moving to it.  You are right, the implementation is pretty basic and actually really poorly done.  Going in and removing cruft and doing the styles right is on the roadmap.  I think right now there is a lot of duplication and also unused styles.  So yeah a refactor PR would be awesome, but expect to find a bit of a mess between the LESS styles and hard coded CSS in base.css.

I have some other suggestions on CSS from another contributor that I need to create issues for (he emailed me.)
